# Generated by Django 3.2.6 on 2021-11-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20211115_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seo',
            name='site_views',
            field=models.IntegerField(default=0),
        ),
    ]
