# Generated by Django 4.0.9 on 2025-06-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_project_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.FileField(upload_to='articles/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.FileField(upload_to='projects/images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='services/icons/'),
        ),
    ]
